#!/bin/sh

PROGRAM="check_pm"
REQUIRED_ARGS=1
PROVIDED_ARGS=$#
COMMAND=$1
PKG_MGR=0

check_args() {
  if [ "$REQUIRED_ARGS" != "$PROVIDED_ARGS" ];
  then
    echo "\nERROR: incorrect number of arguments.\n"
    echo "\nPlease provide exactly one argument:"
    echo ""
    echo "$PROGRAM command_name"
    exit 1
  fi
  return 0
}

# section formatter
function topic() {
  echo "-----> $*"
}

# output formatter
function indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";;
    *)      sed -u "$c";;
  esac
}

# detect the linux distribution
which_path() {
  topic "Looking for $COMMAND on \$PATH:"
  if which $COMMAND > /dev/null 2>&1; then
    echo "$COMMAND is installed at $(which $COMMAND)" | indent
    return 0
  else
    echo "$COMMAND not found" | indent
    return 1
  fi;
}

which_version() {
  echo ""
  topic "Version:"
  if $COMMAND --version > /dev/null 2>&1; then
    $COMMAND --version 2>&1 | indent
    return 0
  elif $COMMAND -v > /dev/null 2>&1; then
    $COMMAND -v 2>&1 | indent
    return 0
  elif $COMMAND version > /dev/null 2>&1; then
    $COMMAND version 2>&1 | indent
    return 0
  else
    echo "unknown" | indent
    return 1
  fi;
}

which_lsof() {
  if which lsof > /dev/null 2>&1; then
    if lsof $(which $COMMAND) > /dev/null 2>&1; then
      echo ""
      topic "Instances:"
      lsof $(which $COMMAND) | indent
      return 0
    fi
  else
    return 0
  fi
}

which_netstat() {
  if which netstat > /dev/null 2>&1; then
    if netstat -ltnp | grep $COMMAND > /dev/null 2>&1; then
      echo ""
      topic "Open ports:"
      netstat -ltnp | grep $COMMAND | indent
      return 0
    fi
  else
    return 0
  fi
}

check_args
if which_path; then
  which_version
  which_lsof
  which_netstat
fi
